# Generated by Django 6.0.4 on 2026-05-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='circuit_montage_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/circuits/'),
        ),
        migrations.AddField(
            model_name='project',
            name='connection_table_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/connections/'),
        ),
    ]
