# Generated by Django 6.0.4 on 2026-06-27 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_project_image_project_circuit_montage_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='components',
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'ملف شخصي', 'verbose_name_plural': 'ملفات المستخدمين'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'مشروع', 'verbose_name_plural': 'المشاريع'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='حالة الموافقة'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='project',
            name='circuit_montage_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/circuits/', verbose_name='صورة مخطط الدائرة'),
        ),
        migrations.AlterField(
            model_name='project',
            name='code_snippet',
            field=models.TextField(blank=True, verbose_name='كود البرمجة'),
        ),
        migrations.AlterField(
            model_name='project',
            name='connection_table_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/connections/', verbose_name='صورة جدول التوصيلات'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='وصف شامل'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان المشروع'),
        ),
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.AddField(
            model_name='project',
            name='components',
            field=models.TextField(blank=True, default='', verbose_name='قائمة مكونات'),
        ),
    ]
